steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['install']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/proyectocomponentes-9f935/dockerfile', '.']

- name: 'gcr.io/proyectocomponentes-9f935/gcloud'
  args: ['info']
- name: 'gcr.io/proyectocomponentes-9f935/gcloud-slim'
  args: ['info']

- name: 'gcr.io/proyectocomponentes-9f935/gcloud'
  args: ['source', 'repos', 'clone', 'default']

images: ['gcr.io/proyectocomponentes-9f935/dockerfile:latest']