steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['install']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$proyectocomponentes-9f935/quick-start', '.']
images: ['gcr.io/proyectocomponentes-9f935/quick-start']
